language: go

install:
  - go get github.com/pborman/uuid
  - go get gopkg.in/LeisureLink/httpsig.v1
  - go get gopkg.in/dgrijalva/jwt-go.v3

go:
  - 1.5.4
  - 1.6.4
  - 1.7.6
  - 1.8.3
  - 1.9

notifications:
  email:
    - ian@getstream.io

branches:
  only:
  - master
  - dev

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  allow_failures:
    - go: 1.9
